# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release
on:
    release:
        types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    # Checkout the exact commit tagged on the release.
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: src/CleanArchitecture.ValidationRules.Types/CleanArchitecture.ValidationRules.Types.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
    - name: Publish  
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:   
       PROJECT_FILE_PATH: src/CleanArchitecture.ValidationRules.Types.Analyzers/CleanArchitecture.ValidationRules.Types.Analyzers.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
